import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { AOSInit } from "@/components/aos-init";
// import { StoreProvider } from "@/context/store_context";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito.variable} h-full antialiased`}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        />
      </head>
      <body className="min-h-full flex flex-col">
        <AOSInit />
        {/*<StoreProvider>*/}
        {children}
        {/*</StoreProvider>*/}
      </body>
    </html>
  );
}
